name: CheezTrails
main: trails.CheezTrails
author: Explodncheez
description: Player particle trails...
version: 1.1
api-version: 1.13
softdepend: [CheezUtils]

commands:
   trails:
      aliases: [trail]
      default: true